### health check
GET https://ecommerce-api-05ik.onrender.com/api/health


### Auth Routes
POST https://ecommerce-api-05ik.onrender.com/api/auth/register
Content-Type: application/json

{
    "name": "testuser",
    "email": "testuser@example.com",
    "password": "password123",
    "role": "customer"
}

### Get all users
GET https://ecommerce-api-05ik.onrender.com/api/auth/users
### health check from localhost
GET http://localhost:3000/api/health

### register from localhost
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "testuser",
    "email": "testuser2@example.com",
    "passwordHash": "password123",
    "role": "customer"
}

### get all users from localhost
GET http://localhost:3000/api/auth/users



### Product Routes



### get all products from localhost
GET http://localhost:3000/api/products

### get product by id from localhost
GET http://localhost:3000/api/products/productIdHere

### create a new product 
POST http://localhost:3000/api/products 
Content-Type: application/json

{
    "name": "Sample Product",
    "description": "This is a sample product.",
    "price": 19.99,
    "category": "Sample Category",
    "stock": 100,
    "sku": "P-001",
    "quantity": 50
}

### update a product by id
PUT http://localhost:3000/api/products/productIdHere
Content-Type: application/json
{
    "name": "Updated Product",
    "description": "This is an updated product description.",
    "price": 29.99,
    "category": "Updated Category",
    "stock": 150,
    "sku": "P-001-U",
    "quantity": 75
}
### delete a product by id
DELETE http://localhost:3000/api/products/productIDHere
